workflow:
  rules: 
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    
stages:
  - update-apps

update-job:
  stage: update-apps
  image: ghcr.io/catthehacker/ubuntu:act-latest@sha256:c710431fbad9eb3bcb102d04e5ff74fbd0ce6e383f78afebfb3770a1a817fdf9
  script:
    - git config user.name "App auto updater"
    - git config user.email "hahelp@uni-bremen.de"
    - git remote set-url --push origin $CI_REPOSITORY_URL
    - python .gitlab/ha-app-repo-updater.py
    - git push origin HEAD:$CI_COMMIT_REF_NAME
